const Ahquabi = {
  group: 'Lake Ahquabi',
  collections: [
    {
      collection: 'Sunrise at Lake Ahquabi',
      added: 'August 28, 2016',
      time: 1472384100000,
      items: [
        {
          name: 'ahquabi-001-1',
          image: './deck/ahquabi-001/m7gcge3azl.jpg',
          backgroundUrl: './deck/ahquabi-001/m7gcge3azl.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-11',
          image: './deck/ahquabi-001/d7yj0fyw6n.jpg',
          backgroundUrl: './deck/ahquabi-001/d7yj0fyw6n.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-5',
          image: './deck/ahquabi-001/f3nujitw1z.jpg',
          backgroundUrl: './deck/ahquabi-001/f3nujitw1z.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-15',
          image: './deck/ahquabi-001/q277z5zq16.jpg',
          backgroundUrl: './deck/ahquabi-001/q277z5zq16.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-14',
          image: './deck/ahquabi-001/nupyo4fa38.jpg',
          backgroundUrl: './deck/ahquabi-001/nupyo4fa38.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-2',
          image: './deck/ahquabi-001/ae0hsmookn.jpg',
          backgroundUrl: './deck/ahquabi-001/ae0hsmookn.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-3',
          image: './deck/ahquabi-001/jebaur7cyk.jpg',
          backgroundUrl: './deck/ahquabi-001/jebaur7cyk.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-4',
          image: './deck/ahquabi-001/z9xci8aobl.jpg',
          backgroundUrl: './deck/ahquabi-001/z9xci8aobl.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-10',
          image: './deck/ahquabi-001/i73ojd3fhj.jpg',
          backgroundUrl: './deck/ahquabi-001/i73ojd3fhj.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-7',
          image: './deck/ahquabi-001/k2lpjem5h7.jpg',
          backgroundUrl: './deck/ahquabi-001/k2lpjem5h7.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-6',
          image: './deck/ahquabi-001/frgnx6r0u7.jpg',
          backgroundUrl: './deck/ahquabi-001/frgnx6r0u7.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-9',
          image: './deck/ahquabi-001/hlip6gs2im.jpg',
          backgroundUrl: './deck/ahquabi-001/hlip6gs2im.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-13',
          image: './deck/ahquabi-001/mv2ou2qnn7.jpg',
          backgroundUrl: './deck/ahquabi-001/mv2ou2qnn7.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-16',
          image: './deck/ahquabi-001/r1bd0g2ojo.jpg',
          backgroundUrl: './deck/ahquabi-001/r1bd0g2ojo.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'ahquabi-001-17',
          image: './deck/ahquabi-001/u62jih6zd4.jpg',
          backgroundUrl: './deck/ahquabi-001/u62jih6zd4.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina', 'hero'],
        },
        {
          name: 'ahquabi-001-18',
          image: './deck/ahquabi-001/v6lb730veg.jpg',
          backgroundUrl: './deck/ahquabi-001/v6lb730veg.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
      ],
    },
    {
      collection: 'A Summer\'s Day at Ahquabi',
      added: 'July 6, 2018',
      time: 1530837000 * 1000,
      items: [
        {
          name: 'oKgFjoNVNaXpwBcj',
          image: './deck/ahquabi-002/oKgFjoNVNaXpwBcj.jpg',
          backgroundUrl: './deck/ahquabi-002/oKgFjoNVNaXpwBcj.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina', 'hero'],
        },
        {
          name: 'raEsXNQGtiVoypVE',
          image: './deck/ahquabi-002/raEsXNQGtiVoypVE.jpg',
          backgroundUrl: './deck/ahquabi-002/raEsXNQGtiVoypVE.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'LSMREjHr0yaLbcYA',
          image: './deck/ahquabi-002/LSMREjHr0yaLbcYA.jpg',
          backgroundUrl: './deck/ahquabi-002/LSMREjHr0yaLbcYA.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
        {
          name: 'TlGDXvLOfewWugYk',
          image: './deck/ahquabi-002/TlGDXvLOfewWugYk.jpg',
          backgroundUrl: './deck/ahquabi-002/TlGDXvLOfewWugYk.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
        },
      ],
    },
  ],
};

export default Ahquabi;
