const BuxtonPark = {
  group: 'Simpson College',
  collections: [
    {
      collection: 'Buxton Park Arboretum',
      added: 'September 11, 2016',
      time: 1473570000000,
      items: [
        {
          name: 'VAxUPCG7Umra',
          image: './deck/buxton-001/VAxUPCG7Umra.jpg',
          backgroundUrl: './deck/buxton-001/VAxUPCG7Umra.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina', 'hero'],
          categories: [],
        },
        {
          name: 'h4rRBArayluX',
          image: './deck/buxton-001/h4rRBArayluX.jpg',
          backgroundUrl: './deck/buxton-001/h4rRBArayluX.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: 'kFCsBvwNdkoj',
          image: './deck/buxton-001/kFCsBvwNdkoj.jpg',
          backgroundUrl: './deck/buxton-001/kFCsBvwNdkoj.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: '7FRGZzbYltGk',
          image: './deck/buxton-001/7FRGZzbYltGk.jpg',
          backgroundUrl: './deck/buxton-001/7FRGZzbYltGk.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: 'IdVxtxZ2r3Zz',
          image: './deck/buxton-001/IdVxtxZ2r3Zz.jpg',
          backgroundUrl: './deck/buxton-001/IdVxtxZ2r3Zz.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: 'TQ0AYLBIRGgr',
          image: './deck/buxton-001/TQ0AYLBIRGgr.jpg',
          backgroundUrl: './deck/buxton-001/TQ0AYLBIRGgr.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: 'vQpKJB9PzaYK',
          image: './deck/buxton-001/vQpKJB9PzaYK.jpg',
          backgroundUrl: './deck/buxton-001/vQpKJB9PzaYK.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: 'L5LPHzrteKQE',
          image: './deck/buxton-001/L5LPHzrteKQE.jpg',
          backgroundUrl: './deck/buxton-001/L5LPHzrteKQE.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
        {
          name: 'GB2HRyYuBnsl',
          image: './deck/buxton-001/GB2HRyYuBnsl.jpg',
          backgroundUrl: './deck/buxton-001/GB2HRyYuBnsl.jpg',
          backgroundPosition: {
            x: 0,
            y: 0,
          },
          height: 576,
          width: 1024,
          tags: ['retina'],
          categories: [],
        },
      ],
    }],
};

export default BuxtonPark;
