const RedRock = {
  group: 'Pella, Iowa',
  collections: [{
    collection: 'Lake Red Rock',
    added: 'June 17, 2016',
    time: 1466139600000,
    items: [
      {
        name: '6SCNCQjEbKLS',
        image: './deck/red-rock-001-comp/6SCNCQjEbKLS.jpg',
        backgroundUrl: './deck/red-rock-001-comp/6SCNCQjEbKLS.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina', 'hero'],
        categories: [],
      },
      {
        name: 'Q4gC5e4ahBQf',
        image: './deck/red-rock-001-comp/Q4gC5e4ahBQf.jpg',
        backgroundUrl: './deck/red-rock-001-comp/Q4gC5e4ahBQf.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'ttZnr9btOCIg',
        image: './deck/red-rock-001-comp/ttZnr9btOCIg.jpg',
        backgroundUrl: './deck/red-rock-001-comp/ttZnr9btOCIg.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'bFVoxgW2vrMU',
        image: './deck/red-rock-001-comp/bFVoxgW2vrMU.jpg',
        backgroundUrl: './deck/red-rock-001-comp/bFVoxgW2vrMU.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'rQxrYgxK5ueg',
        image: './deck/red-rock-001-comp/rQxrYgxK5ueg.jpg',
        backgroundUrl: './deck/red-rock-001-comp/rQxrYgxK5ueg.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'y1brSBdJsz1x',
        image: './deck/red-rock-001-comp/y1brSBdJsz1x.jpg',
        backgroundUrl: './deck/red-rock-001-comp/y1brSBdJsz1x.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: '7gvpYum0paZc',
        image: './deck/red-rock-001-comp/7gvpYum0paZc.jpg',
        backgroundUrl: './deck/red-rock-001-comp/7gvpYum0paZc.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: '28bTvpC3foA8',
        image: './deck/red-rock-001-comp/28bTvpC3foA8.jpg',
        backgroundUrl: './deck/red-rock-001-comp/28bTvpC3foA8.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'ZE8ptBiVDddI',
        image: './deck/red-rock-001-comp/ZE8ptBiVDddI.jpg',
        backgroundUrl: './deck/red-rock-001-comp/ZE8ptBiVDddI.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'vbrYdfZ4Q7iD',
        image: './deck/red-rock-001-comp/vbrYdfZ4Q7iD.jpg',
        backgroundUrl: './deck/red-rock-001-comp/vbrYdfZ4Q7iD.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'BRkLfrZZjhvu',
        image: './deck/red-rock-001-comp/BRkLfrZZjhvu.jpg',
        backgroundUrl: './deck/red-rock-001-comp/BRkLfrZZjhvu.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
    ],
  },
  {
    collection: 'Tulip Time Festival',
    added: 'June 17, 2016',
    time: 1466139600000,
    items: [
      {
        name: 'tt-001-1',
        image: './deck/tt-001/IMG_4194.jpg',
        backgroundUrl: './deck/tt-001/dN3YpnolEQ6w.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina', 'hero'],
        categories: [],
      },
      {
        name: 'tt-001-2',
        image: './deck/tt-001/IMG_3982.jpg',
        backgroundUrl: './deck/tt-001/6aXi9IkiX9nV.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 1024,
        width: 576,
        tags: ['retina', 'portrait'],
        categories: [],
      },
      {
        name: 'tt-001-3',
        image: './deck/tt-001/IMG_4216.jpg',
        backgroundUrl: './deck/tt-001/xkKSnV06F812.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'tt-001-4',
        image: './deck/tt-001/IMG_3897.jpg',
        backgroundUrl: './deck/tt-001/GQolk08aqRxg.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'tt-001-5',
        image: './deck/tt-001/IMG_4013.jpg',
        backgroundUrl: './deck/tt-001/9An2cinOrw3U.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'tt-001-6',
        image: './deck/tt-001/IMG_4228.jpg',
        backgroundUrl: './deck/tt-001/6C889HFaTOYl.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 1024,
        width: 576,
        tags: ['retina', 'portrait'],
        categories: [],
      },
      {
        name: 'tt-001-7',
        image: './deck/tt-001/IMG_4112.jpg',
        backgroundUrl: './deck/tt-001/GHzXF5ANbdtU.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 1024,
        width: 576,
        tags: ['retina', 'portrait'],
        categories: [],
      },
      {
        name: 'tt-001-8',
        image: './deck/tt-001/IMG_4125.jpg',
        backgroundUrl: './deck/tt-001/R9FDrpUtv5Cr.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 1024,
        width: 576,
        tags: ['retina', 'portrait'],
        categories: [],
      },
      {
        name: 'tt-001-9',
        image: './deck/tt-001/IMG_4244.jpg',
        backgroundUrl: './deck/tt-001/1qonUa3LCv3o.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 1024,
        width: 576,
        tags: ['retina', 'portrait'],
        categories: [],
      },
      {
        name: 'tt-001-10',
        image: './deck/tt-001/IMG_4172.jpg',
        backgroundUrl: './deck/tt-001/gKFWTK3OGCvH.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 1024,
        width: 576,
        tags: ['retina', 'portrait'],
        categories: [],
      },
      {
        name: 'tt-001-11',
        image: './deck/tt-001/IMG_3915.jpg',
        backgroundUrl: './deck/tt-001/vq7tOU2VuPEZ.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'tt-001-12',
        image: './deck/tt-001/IMG_4288.jpg',
        backgroundUrl: './deck/tt-001/vts4uQvL7uAv.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'tt-001-13',
        image: './deck/tt-001/IMG_4430.jpg',
        backgroundUrl: './deck/tt-001/2YVcEw62Ojl3.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
      {
        name: 'tt-001-14',
        image: './deck/tt-001/IMG_4450.jpg',
        backgroundUrl: './deck/tt-001/HRxhTJYHoGQ1.jpg',
        backgroundPosition: {
          x: 0,
          y: 0,
        },
        height: 576,
        width: 1024,
        tags: ['retina'],
        categories: [],
      },
    ],
  }],
};

export default RedRock;
