const WoodlandMounds = {
  collections: [
    {
      added: 'October 28, 2018',
      captureTime: 1505001600000,
      categories: [],
      collection: 'Bugs, Mushrooms, and Prairie Grass',
      hidden: false,
      items: [
        {
          name: 'ExpgzychKdrwmbd0',
          image: './deck/woodland-mounds-002/ExpgzychKdrwmbd0.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/ExpgzychKdrwmbd0.jpg',
          categories: [],
          height: 576,
          tags: ['retina', 'hero'],
          width: 1024,
        },
        {
          name: 'TYhwXyJfyE51ELMA',
          image: './deck/woodland-mounds-002/TYhwXyJfyE51ELMA.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/TYhwXyJfyE51ELMA.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'sEYPYcOksK25rxZ7',
          image: './deck/woodland-mounds-002/sEYPYcOksK25rxZ7.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/sEYPYcOksK25rxZ7.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'GKqG89j4Innr1Z2I',
          image: './deck/woodland-mounds-002/GKqG89j4Innr1Z2I.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/GKqG89j4Innr1Z2I.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'DmgIPX6htsmi4LQc',
          image: './deck/woodland-mounds-002/DmgIPX6htsmi4LQc.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/DmgIPX6htsmi4LQc.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'FH0iY3nCPKs2JFRt',
          image: './deck/woodland-mounds-002/FH0iY3nCPKs2JFRt.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/FH0iY3nCPKs2JFRt.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'LKN4G2o4pmZqxoQh',
          image: './deck/woodland-mounds-002/LKN4G2o4pmZqxoQh.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/LKN4G2o4pmZqxoQh.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'GeKWeNUkpnefsJYL',
          image: './deck/woodland-mounds-002/GeKWeNUkpnefsJYL.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/GeKWeNUkpnefsJYL.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'UhwnlByDQB7jnwpT',
          image: './deck/woodland-mounds-002/UhwnlByDQB7jnwpT.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-002/UhwnlByDQB7jnwpT.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
      ],
      tags: [],
      time: 1540771200000,
    },
    {
      added: 'July 8, 2017',
      captureTime: null,
      categories: [],
      collection: 'Quiet of Woodland Mounds',
      hidden: false,
      items: [
        {
          name: '9RpVtuhxjivl',
          image: './deck/woodland-mounds-001/9RpVtuhxjivl.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-001/9RpVtuhxjivl.jpg',
          categories: [],
          height: 576,
          tags: ['retina', 'hero'],
          width: 1024,
        },
        {
          name: 'WpPApLRpHH6E',
          image: './deck/woodland-mounds-001/WpPApLRpHH6E.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-001/WpPApLRpHH6E.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: 'QIYYaBDhSVCU',
          image: './deck/woodland-mounds-001/QIYYaBDhSVCU.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-001/QIYYaBDhSVCU.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
        {
          name: '63F45ue5ejUl',
          image: './deck/woodland-mounds-001/63F45ue5ejUl.jpg',
          backgroundPosition: { x: 0, y: 0 },
          backgroundUrl: './deck/woodland-mounds-001/63F45ue5ejUl.jpg',
          categories: [],
          height: 576,
          tags: ['retina'],
          width: 1024,
        },
      ],
      tags: [],
      time: 1499472000000,
    },
  ],
  group: 'Woodland Mounds',
};

export default WoodlandMounds;